-- Seed train catalogue (idempotent via MERGE on unique train_number).
-- 64 seats per class (8x8 layout) for every train.

MERGE INTO trains (train_number, train_name, total_seats_per_class, active)
    KEY (train_number) VALUES ('12621', 'Tamil Nadu Express', 64, TRUE);

MERGE INTO trains (train_number, train_name, total_seats_per_class, active)
    KEY (train_number) VALUES ('11041', 'Chennai Mumbai Express', 64, TRUE);

MERGE INTO trains (train_number, train_name, total_seats_per_class, active)
    KEY (train_number) VALUES ('12951', 'Mumbai Rajdhani', 64, TRUE);

MERGE INTO trains (train_number, train_name, total_seats_per_class, active)
    KEY (train_number) VALUES ('12009', 'Shatabdi Express', 64, TRUE);

-- Seed schedules. Train ids are 1..4 in the insertion order above.
-- At least two Chennai -> Mumbai schedules exist (acceptance criteria).
MERGE INTO schedules (id, train_id, from_station, to_station, departure_time, arrival_time,
                      journey_date, fare_sleeper, fare_ac3, fare_ac2)
    KEY (id) VALUES (1, 1, 'Chennai', 'Mumbai', '22:00:00', '07:15:00', DATE '2026-08-15', 800.00, 1400.00, 2000.00);

MERGE INTO schedules (id, train_id, from_station, to_station, departure_time, arrival_time,
                      journey_date, fare_sleeper, fare_ac3, fare_ac2)
    KEY (id) VALUES (2, 2, 'Chennai', 'Mumbai', '11:40:00', '04:30:00', DATE '2026-08-15', 850.00, 1450.00, 2100.00);

MERGE INTO schedules (id, train_id, from_station, to_station, departure_time, arrival_time,
                      journey_date, fare_sleeper, fare_ac3, fare_ac2)
    KEY (id) VALUES (3, 3, 'Mumbai', 'Delhi', '17:00:00', '08:35:00', DATE '2026-08-15', 900.00, 1600.00, 2300.00);

MERGE INTO schedules (id, train_id, from_station, to_station, departure_time, arrival_time,
                      journey_date, fare_sleeper, fare_ac3, fare_ac2)
    KEY (id) VALUES (4, 4, 'Ahmedabad', 'Mumbai', '06:15:00', '13:10:00', DATE '2026-08-16', 500.00, 900.00, 1300.00);

-- Seeding schedules with explicit ids does NOT advance H2's identity sequence,
-- which still starts at 1. Restart it past the highest seeded id so that
-- application-generated schedules never collide with the seed rows.
ALTER TABLE schedules ALTER COLUMN id RESTART WITH 5;

-- Seed default admin account (idempotent via MERGE on unique email).
-- Password is BCrypt-hashed. The hash below corresponds to the plaintext: password
-- To use a different password, replace the hash with one generated by BCrypt
-- (see README for a one-line command).
MERGE INTO users (full_name, email, password, role, created_at)
    KEY (email)
    VALUES ('Rail Admin', 'admin@raileasy.com',
            '$2a$12$OoGOTkbopIhS0H5UstN2G.4vy42md8JsdNz6TJVXEMVXBWcPhR2bW',
            'ADMIN', CURRENT_TIMESTAMP);
